In [1]:
import numpy as np
import random
input_nodes = 10
hidden_nodes = 5
output_nodes = 7
wih = np.random.randint(-10, 10, (hidden_nodes, input_nodes))
wih

array([[ -1,   2,   3,   0,  -9,   8,  -8,  -4,   6,   2],
       [  1, -10,  -2,   1,  -4,  -8,   1,   0,  -8,   4],
       [ -2,   3,   6,   7, -10,   3,  -3,  -7,   1,  -3],
       [  1,   5,   8,   4, -10,  -8,   9,  -5,   3,  -6],
       [  1,  -2,  -9,   9,  -2,  -3,   2,  -4,  -1,   5]])

In [2]:
active_input_percentage = 0.7
active_input_nodes = int(input_nodes * active_input_percentage)
active_input_indices = sorted(random.sample(range(0, input_nodes),active_input_nodes))
active_input_indices

[0, 2, 3, 4, 6, 7, 9]

In [3]:
wih_old = wih.copy()
wih = wih[:, active_input_indices]
wih

array([[ -1,   3,   0,  -9,  -8,  -4,   2],
       [  1,  -2,   1,  -4,   1,   0,   4],
       [ -2,   6,   7, -10,  -3,  -7,  -3],
       [  1,   8,   4, -10,   9,  -5,  -6],
       [  1,  -9,   9,  -2,   2,  -4,   5]])

In [5]:
who = np.random.randint(-10, 10, (output_nodes, hidden_nodes))
print(who)
active_hidden_percentage = 0.7
active_hidden_nodes = int(hidden_nodes * active_hidden_percentage)
active_hidden_indices = sorted(random.sample(range(0, hidden_nodes),
active_hidden_nodes))
print(active_hidden_indices)
who_old = who.copy()
who = who[:, active_hidden_indices]
print(who)


[[ -4  -4   1  -2  -1]
 [  8  -6   9  -4  -3]
 [ -1   1   0   4 -10]
 [ -9  -5  -7  -1 -10]
 [  6   7  -5   3   6]
 [  6  -7  -7 -10  -4]
 [ -9  -4  -1   6   4]]
[0, 1, 4]
[[ -4  -4  -1]
 [  8  -6  -3]
 [ -1   1 -10]
 [ -9  -5 -10]
 [  6   7   6]
 [  6  -7  -4]
 [ -9  -4   4]]


In [6]:
wih = wih[active_hidden_indices]
wih

array([[-1,  3,  0, -9, -8, -4,  2],
       [ 1, -2,  1, -4,  1,  0,  4],
       [ 1, -9,  9, -2,  2, -4,  5]])

In [8]:
import numpy as np
import random
input_nodes = 10
hidden_nodes = 5
output_nodes = 7
wih = np.random.randint(-10, 10, (hidden_nodes, input_nodes))
print("wih: \n", wih)
who = np.random.randint(-10, 10, (output_nodes, hidden_nodes))
print("who:\n", who)
active_input_percentage = 0.7
active_hidden_percentage = 0.7
active_input_nodes = int(input_nodes * active_input_percentage)
active_input_indices = sorted(random.sample(range(0, input_nodes),
active_input_nodes))
print("\nactive input indices: ", active_input_indices)
active_hidden_nodes = int(hidden_nodes * active_hidden_percentage)
active_hidden_indices = sorted(random.sample(range(0, hidden_nodes),active_hidden_nodes))
print("active hidden indices: ", active_hidden_indices)
wih_old = wih.copy()
wih = wih[:, active_input_indices]
print("\nwih after deactivating input nodes:\n", wih)
wih = wih[active_hidden_indices]
print("\nwih after deactivating hidden nodes:\n", wih)
who_old = who.copy()
who = who[:, active_hidden_indices]
print("\nwih after deactivating hidden nodes:\n", who)

wih: 
 [[ -8   5   7  -7   6   8  -4  -8  -4   6]
 [  5  -5  -8   9   1   6   0  -6   7  -3]
 [ -8  -8   7  -9   4   2  -5   2   3  -3]
 [  0  -8  -7   4   6  -8   8   4   6  -6]
 [  2   1  -6   6  -7  -1   2  -6  -9 -10]]
who:
 [[ -2  -9  -7   8 -10]
 [ -9   9   1   4   6]
 [  4   4   1  -8  -3]
 [ -4   6  -1  -2  -7]
 [-10  -3   9   9   3]
 [ -4  -8   4   5   7]
 [ -5   9   8   1  -5]]

active input indices:  [0, 1, 3, 4, 5, 7, 8]
active hidden indices:  [0, 2, 3]

wih after deactivating input nodes:
 [[-8  5 -7  6  8 -8 -4]
 [ 5 -5  9  1  6 -6  7]
 [-8 -8 -9  4  2  2  3]
 [ 0 -8  4  6 -8  4  6]
 [ 2  1  6 -7 -1 -6 -9]]

wih after deactivating hidden nodes:
 [[-8  5 -7  6  8 -8 -4]
 [-8 -8 -9  4  2  2  3]
 [ 0 -8  4  6 -8  4  6]]

wih after deactivating hidden nodes:
 [[ -2  -7   8]
 [ -9   1   4]
 [  4   1  -8]
 [ -4  -1  -2]
 [-10   9   9]
 [ -4   4   5]
 [ -5   8   1]]
