In [1]:
import numpy as np
from scipy.stats import truncnorm

In [2]:
def truncated_normal(mean=0, sd=1, low=0, upp=10):
  return truncnorm((low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)

In [3]:
class NeuralNetwork:
  def __init__(self,no_of_in_nodes,no_of_out_nodes,no_of_hidden_nodes,learning_rate):
    self.no_of_in_nodes = no_of_in_nodes
    self.no_of_out_nodes = no_of_out_nodes
    self.no_of_hidden_nodes = no_of_hidden_nodes
    self.learning_rate = learning_rate
    self.create_weight_matrices()

  def create_weight_matrices(self):
    rad = 1 / np.sqrt(self.no_of_in_nodes)
    X = truncated_normal(mean=0, sd=1, low=-rad, upp=rad)
    self.weights_in_hidden = X.rvs((self.no_of_hidden_nodes,
    self.no_of_in_nodes))
    rad = 1 / np.sqrt(self.no_of_hidden_nodes)
    X = truncated_normal(mean=0, sd=1, low=-rad, upp=rad)
    self.weights_hidden_out = X.rvs((self.no_of_out_nodes,
    self.no_of_hidden_nodes))

    def train(self):
      pass

    def run(self):
      pass


In [4]:
simple_network = NeuralNetwork(no_of_in_nodes = 3,no_of_out_nodes = 2,no_of_hidden_nodes = 4,learning_rate = 0.1)
print(simple_network.weights_in_hidden)
print(simple_network.weights_hidden_out)


[[-0.08234362 -0.21858088  0.05827423]
 [ 0.41090402  0.01621957  0.17294828]
 [-0.55799222 -0.42784174 -0.04694028]
 [-0.55000529  0.49560647  0.32656797]]
[[ 0.33724575 -0.39786162 -0.0996352  -0.10798451]
 [-0.09055336 -0.03416961 -0.17451843 -0.45613381]]
