In [1]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
indices = np.random.permutation(len(iris.data))
indices

array([ 31,   8,  34,  12,  40,  61,  80,  98, 145, 108, 144,  89, 135,
       119,  30,  85,  26,  36,  91, 124,   3,  99, 126,  50,  15,  44,
        71,  81,  78,  38, 112, 142,  21,  79,  60, 117, 111,  29,  53,
       121, 130, 101, 132, 133,  49,   9, 110,  90,  74, 114,   6,  22,
         1,  27,  17,   5,  77,  92,  56, 147,  69,  94,  48,  72,  32,
         0, 105, 109,  59,   2,  84,  45,  54,  58, 104,  67,  23,  37,
       143,  73, 102,  47,  95, 136, 148,  63, 115,   4, 149,  64,  42,
       129,  18,  97, 125,  19,  52,  28,  16, 118, 127, 141,  57,  39,
        88, 137,  83,   7,  82,  35,  86, 106, 100, 138, 120, 139, 123,
        75,  65, 128,  10,  33,  20, 113,  87, 103,  68,  13,  76,  46,
        66, 134, 122, 116,  43, 146,  14,  62, 107,  41,  70,  93,  51,
        96,  25, 131,  55, 140,  11,  24])

In [4]:
n_test_samples = 12
learnset_data = iris.data[indices[:-n_test_samples]]
learnset_labels = iris.target[indices[:-n_test_samples]]
testset_data = iris.data[indices[-n_test_samples:]]
testset_labels = iris.target[indices[-n_test_samples:]]
print(learnset_data[:4], learnset_labels[:4])
print(testset_data[:4], testset_labels[:4])


[[5.4 3.4 1.5 0.4]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [4.8 3.  1.4 0.1]] [0 0 0 0]
[[7.3 2.9 6.3 1.8]
 [4.5 2.3 1.3 0.3]
 [5.9 3.2 4.8 1.8]
 [5.  2.3 3.3 1. ]] [2 0 1 1]


In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
data, labels = iris.data, iris.target
res = train_test_split(data, labels,
train_size=0.8,
test_size=0.2,
random_state=42)
train_data, test_data, train_labels, test_labels = res
n = 7
print(f"The first {n} data sets:")
print(test_data[:7])
print(f"The corresponding {n} labels:")
print(test_labels[:7])


The first 7 data sets:
[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]]
The corresponding 7 labels:
[1 0 2 1 1 0 1]


In [6]:
import numpy as np
print('All:', np.bincount(labels) / float(len(labels)) * 100.0)
print('Training:', np.bincount(train_labels) / float(len(train_labels)) * 100.0)
print('Test:', np.bincount(test_labels) / float(len(test_labels))* 100.0)


All: [33.33333333 33.33333333 33.33333333]
Training: [33.33333333 34.16666667 32.5       ]
Test: [33.33333333 30.         36.66666667]


In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
data, labels = iris.data, iris.target
res = train_test_split(data, labels,
train_size=0.8,
test_size=0.2,
random_state=42,
stratify=labels)
train_data, test_data, train_labels, test_labels = res
print('All:', np.bincount(labels) / float(len(labels)) * 100.0)
print('Training:', np.bincount(train_labels) / float(len(train_labels)) * 100.0)
print('Test:', np.bincount(test_labels) / float(len(test_labels))* 100.0)


All: [33.33333333 33.33333333 33.33333333]
Training: [33.33333333 33.33333333 33.33333333]
Test: [33.33333333 33.33333333 33.33333333]
