In [3]:
import tensorflow as tf

x = tf.constant(3)
y = tf.constant(5)
final_node = tf.add(x, y)

result = final_node.numpy()
print(result, type(result))


8 <class 'numpy.int32'>


In [4]:
import tensorflow as tf

# Computational Graph:
c1 = tf.constant(0.034, dtype=tf.float64)
c2 = tf.constant(1000.0, dtype=tf.float64)
x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)
final_node = tf.add(x, y)

# No need for explicit session management, just run the final node
result = final_node.numpy()
print(result, type(result))


34.001156 <class 'numpy.float64'>


In [5]:
import tensorflow as tf

# Computational Graph:
c1 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)
c2 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)
x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)
final_node = tf.add(x, y)

# No need for explicit session management, just run the final node
result = final_node.numpy()
print(result, type(result))


[ 23.12 165.62   2.88 162.  ] <class 'numpy.ndarray'>


In [7]:
c1 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)
c2 = tf.constant([3.4, 9.1, -1.2, 9], dtype=tf.float64)
x = tf.multiply(c1, c1)
y = tf.multiply(c1, c2)
final_node = tf.add(x, y)
print(c1)
print(x)
print(final_node)

tf.Tensor([ 3.4  9.1 -1.2  9. ], shape=(4,), dtype=float64)
tf.Tensor([11.56 82.81  1.44 81.  ], shape=(4,), dtype=float64)
tf.Tensor([ 23.12 165.62   2.88 162.  ], shape=(4,), dtype=float64)
