In [2]:
import tensorflow as tf

# Create a TensorFlow session (not needed in TF 2.x)
# session = tf.Session()

# Define the tensor x
x = tf.range(12)

# Print the result of running the tensor x
print(x.numpy())

# Reshape x into a 3x4 matrix
x2 = tf.reshape(x, shape=(3, 4))

# Sum along the first dimension (rows) of x2
x2_sum = tf.reduce_sum(x2, axis=0)

# Print the result
print(x2_sum.numpy())

# Create a 5x5 identity matrix
x3 = tf.eye(5)

# Print the result
print(x3.numpy())


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 15 18 21]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
import numpy as np
x = np.arange(12)
print(x)
x2 = x.reshape((3, 4))
res = x2.sum(axis=0)
print(res)
x3 = np.eye(5, 5)
print(x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 15 18 21]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
